[package]
name = "oaidl-safe"
version = "0.1.0"
authors = ["ZerothLaw <trinioler@gmail.com>"]

[dependencies]
rust_decimal = "0.10.1"
widestring = "0.4.0"
winapi = {version = "0.3.6", features = ["oaidl", "oleauto", "wtypes"]}
